name: dotnet package

on: [push]

jobs:
  build:


    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Install dependencies
        run: dotnet workload install wasm-tools

      - name: Create the JS lib package
        run: dotnet publish SuperCrossPlatformLib -c Release

      - name: Make the package
        shell: pwsh
        run: |
          .\make-package.ps1

      - name: Push generated lib to JS repository
        env:
            SSH_API_WRITE: ${{ secrets.SSH_API_WRITE }}
            DESTINATION_BRANCH: 'main'
            COMMIT_EMAIL: 'andrey.gazzaev@gmail.com'
            COMMIT_USERNAME: 'andrey-gazzaev'
            DESTINATION_USERNAME: 'andrey-gazzaev'
            DESTINATION_REPOSITORY: 'SuperCrossPlatformLibAutoGen'
            SOURCE_FILES: 'SuperCrossPlatformLib/bin/Release/net9.0/browser-wasm/AppBundle'
            CLONE_DIRECTORY: 'SuperCrossPlatformLibAutoGen'
            DESTINATION_DIRECTORY: '/'
            GITHUB_REPOSITORY: ${{ github.event.repository.name }}
            GITHUB_SHA: ${{ github.sha }}
        run: |
          rm -rf .git 

          echo
          echo "##### Cloning destination git repository - https://$SSH_API_WRITE@github.com/$DESTINATION_USERNAME/$DESTINATION_REPOSITORY.git #####"

          git clone --single-branch --branch "$DESTINATION_BRANCH" "https://$SSH_API_WRITE@github.com/$DESTINATION_USERNAME/$DESTINATION_REPOSITORY.git" "$CLONE_DIRECTORY"
          ls -la "$CLONE_DIRECTORY"
 
          echo
          echo "##### Copying contents to git repo #####"

          cd $CLONE_DIRECTORY/$DESTINATION_DIRECTORY

          git config --global user.email "$COMMIT_EMAIL"
          git config --global user.name "$COMMIT_USERNAME"

          git checkout $DESTINATION_BRANCH

          git pull

          cd ..

          cp -rvf $SOURCE_FILES/* "$CLONE_DIRECTORY/$DESTINATION_DIRECTORY"

          cd $CLONE_DIRECTORY/$DESTINATION_DIRECTORY

          echo
          echo "##### Adding git commit #####"

          ORIGIN_COMMIT="https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA"

          git add .
          git status

          git commit -m "$ORIGIN_COMMIT"

          echo
          echo "##### Pushing git commit #####"

          git push origin "$DESTINATION_BRANCH"